import {
  AdminContactMessage,
  AdminTradeApplication,
  AdminNewsletterSubscription,
} from '../types';

export const mockContactMessages: AdminContactMessage[] = [
  {
    id: 'msg-01',
    name: 'Elif Karahan',
    email: 'elif.karahan@studioarch.com',
    subject: 'Restoran Projesi İçin Özel Sır Talebi',
    message: 'Karaköy şubemiz için 15 adet heykelsi stoneware vazo düşünüyoruz. RAL 7032 taş grisi tonunda özel sır geliştirmeniz mümkün müdür?',
    status: 'new',
    admin_notes: null,
    reviewed_at: null,
    created_at: '2026-08-26T08:30:00.000Z',
  },
  {
    id: 'msg-02',
    name: 'Murat Demir',
    email: 'murat.demir@otelpera.com',
    subject: 'Lobi Alanı İçin Numune ve Katalog',
    message: 'Yeni açılacak butik otelimizin lobi ve suit odaları için katalog ve malzeme numunesi talep etmekteyiz.',
    status: 'read',
    admin_notes: 'Numune kiti kargoya verildi. Takip no: YRT109823',
    reviewed_at: '2026-08-25T14:15:00.000Z',
    created_at: '2026-08-25T11:20:00.000Z',
  },
  {
    id: 'msg-03',
    name: 'Selin Yılmaz',
    email: 'selin@modernliving.com',
    subject: 'Kurumsal Hediye Paketi',
    message: 'Yıl sonu kurumsal müşterilerimiz için 40 adet mini seramik vazo siparişi vermek istiyoruz. Logo mühürleme yapıyor musunuz?',
    status: 'replied',
    admin_notes: 'Özel kutu ve mühürleme detayları e-posta ile iletildi.',
    reviewed_at: '2026-08-24T16:00:00.000Z',
    created_at: '2026-08-24T09:45:00.000Z',
  },
  {
    id: 'msg-04',
    name: 'Ahmet Kaya',
    email: 'ahmet.kaya@gmail.com',
    subject: 'Kargo Teslimat Süresi Hakkında',
    message: 'Sipariş vermeden önce İstanbul içi teslimat süresini öğrenmek istedim. Hafta sonuna yetişir mi?',
    status: 'archived',
    admin_notes: 'Aynı gün kargo bilgisi paylaşıldı ve konu çözüldü.',
    reviewed_at: '2026-08-23T12:00:00.000Z',
    created_at: '2026-08-23T08:10:00.000Z',
  },
];

export const mockTradeApplications: AdminTradeApplication[] = [
  {
    id: 'trade-01',
    company_name: 'Artisan Tasarım & İç Mimarlık Ltd.',
    tax_number: '1234567890',
    tax_office: 'Beşiktaş',
    business_type: 'İç Mimarlık & Tasarım Ofisi',
    contact_person: 'Canan Özdemir',
    email: 'canan@artisantasarim.com',
    phone: '+90 532 111 22 33',
    website: 'https://artisantasarim.com',
    estimated_monthly_volume: '20-50 Adet',
    notes: 'Bodrum ve Çeşme villa projelerimizde sürekli seramik obje kullanımımız bulunmaktadır.',
    status: 'pending',
    admin_notes: null,
    submitted_at: '2026-08-26T07:15:00.000Z',
    reviewed_at: null,
  },
  {
    id: 'trade-02',
    company_name: 'Pera Concept Store',
    tax_number: '9876543210',
    tax_office: 'Beyoğlu',
    business_type: 'Perakende Mağaza & Butik',
    contact_person: 'Burak Tan',
    email: 'burak@peraconcept.com',
    phone: '+90 542 222 33 44',
    website: 'https://peraconcept.com',
    estimated_monthly_volume: '50-100 Adet',
    notes: 'Nişantaşı ve Galata mağazalarımızda koleksiyonunuza yer vermek istiyoruz.',
    status: 'approved',
    admin_notes: 'Vergi levhası ve mağaza fotoğrafları incelendi. Toptan sözleşme onaylandı.',
    submitted_at: '2026-08-25T10:00:00.000Z',
    reviewed_at: '2026-08-25T15:30:00.000Z',
  },
  {
    id: 'trade-03',
    company_name: 'Monolith Otelcilik A.Ş.',
    tax_number: '4567891230',
    tax_office: 'Kadıköy',
    business_type: 'Otel & Restoran İşletmesi',
    contact_person: 'Zeynep Akın',
    email: 'zeynep.akin@monolithhotel.com',
    phone: '+90 533 333 44 55',
    website: 'https://monolithhotel.com',
    estimated_monthly_volume: '100+ Adet',
    notes: 'Kapadokya otel projemiz için 80 adet özel form masa üstü seramik vazo arayışındayız.',
    status: 'more_info_needed',
    admin_notes: 'Mimari yerleşim planı ve istenilen sır kodları talep edildi.',
    submitted_at: '2026-08-24T14:20:00.000Z',
    reviewed_at: '2026-08-24T17:00:00.000Z',
  },
  {
    id: 'trade-04',
    company_name: 'Bireysel Alım Girişimi',
    tax_number: '0000000000',
    tax_office: 'Yok',
    business_type: 'Bireysel',
    contact_person: 'Deniz Kaya',
    email: 'deniz.kaya@example.com',
    phone: '+90 555 999 88 77',
    website: null,
    estimated_monthly_volume: '1-5 Adet',
    notes: 'Evim için toptan fiyatla vazo almak istiyorum.',
    status: 'rejected',
    admin_notes: 'Bireysel başvuru olduğu için perakende mağazaya yönlendirildi.',
    submitted_at: '2026-08-23T11:00:00.000Z',
    reviewed_at: '2026-08-23T13:00:00.000Z',
  },
];

export const mockNewsletterSubscriptions: AdminNewsletterSubscription[] = [
  {
    id: 'news-01',
    normalized_email: 'cem.arslan@gmail.com',
    status: 'active',
    source: 'storefront_footer',
    created_at: '2026-08-26T06:00:00.000Z',
    updated_at: '2026-08-26T06:00:00.000Z',
  },
  {
    id: 'news-02',
    normalized_email: 'asli.demir@studio.com',
    status: 'active',
    source: 'homepage_popup',
    created_at: '2026-08-25T18:30:00.000Z',
    updated_at: '2026-08-25T18:30:00.000Z',
  },
  {
    id: 'news-03',
    normalized_email: 'serkan.yurt@outlook.com',
    status: 'unsubscribed',
    source: 'storefront_footer',
    created_at: '2026-08-20T12:00:00.000Z',
    updated_at: '2026-08-24T09:15:00.000Z',
  },
  {
    id: 'news-04',
    normalized_email: 'nur.celik@design.co',
    status: 'active',
    source: 'checkout_optin',
    created_at: '2026-08-22T14:45:00.000Z',
    updated_at: '2026-08-22T14:45:00.000Z',
  },
];
