import { AdminOrderDetail } from '../types';

export const mockAdminOrders: AdminOrderDetail[] = [
  {
    id: 'ord-test-001',
    order_number: 'VZ-20260829-001',
    customer_id: 'cust-01',
    customer_name: 'Ayşe Yılmaz',
    customer_email: 'ayse@example.com',
    customer_phone: '+90 555 123 4567',
    channel: 'retail',
    status: 'paid',
    currency: 'TRY',
    tax_included: true,
    subtotal_minor: 450000,
    shipping_minor: 15000,
    discount_minor: 0,
    tax_included_minor: 78750,
    total_minor: 465000,
    shipping_carrier: null,
    shipping_tracking_number: null,
    shipping_tracking_url: null,
    cancellation_reason: null,
    admin_notes: null,
    created_at: new Date(Date.now() - 2 * 3600 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 2 * 3600 * 1000).toISOString(),
    paid_at: new Date(Date.now() - 2 * 3600 * 1000).toISOString(),
    cancelled_at: null,
    shipped_at: null,
    delivered_at: null,
    shipping_address: {
      id: 'addr-01',
      user_id: 'cust-01',
      label: 'Ev Adresi',
      recipient_name: 'Ayşe Yılmaz',
      phone: '5551234567',
      address_line1: 'Karaköy Kemankeş Mah. No: 42',
      address_line2: 'Daire: 5',
      district: 'Beyoğlu',
      city: 'İstanbul',
      state_province: null,
      postal_code: '34425',
      country_code: 'TR',
      country_name: 'Türkiye',
      is_default_shipping: true,
      is_default_billing: true,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    billing_address: {
      id: 'addr-01',
      user_id: 'cust-01',
      label: 'Ev Adresi',
      recipient_name: 'Ayşe Yılmaz',
      phone: '5551234567',
      address_line1: 'Karaköy Kemankeş Mah. No: 42',
      address_line2: 'Daire: 5',
      district: 'Beyoğlu',
      city: 'İstanbul',
      state_province: null,
      postal_code: '34425',
      country_code: 'TR',
      country_name: 'Türkiye',
      is_default_shipping: true,
      is_default_billing: true,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    items: [
      {
        id: 'item-01',
        order_id: 'ord-test-001',
        product_id: 'prod-01',
        variant_id: 'var-01',
        sku_snapshot: 'VZ-TERRA-S',
        product_name_snapshot: 'Terra Seramik Vazo',
        variant_name_snapshot: 'Terracotta / Küçük (18cm)',
        image_url_snapshot: 'https://images.unsplash.com/photo-1578749556568-bc2c40e68b61?auto=format&fit=crop&q=80&w=800',
        unit_price_minor: 450000,
        quantity: 1,
        line_total_minor: 450000,
        currency: 'TRY',
        channel: 'retail',
        metadata_snapshot: {},
        created_at: new Date().toISOString(),
      },
    ],
    payments: [
      {
        id: 'pay-001',
        order_id: 'ord-test-001',
        order_number: 'VZ-20260829-001',
        customer_email: 'ayse@example.com',
        provider: 'paytr',
        merchant_oid: 'VZ20260829001TX1',
        status: 'paid',
        expected_amount_minor: 465000,
        refunded_amount_minor: 0,
        currency: 'TRY',
        test_mode: true,
        failure_code: null,
        failure_message_safe: null,
        initiated_at: new Date(Date.now() - 2 * 3600 * 1000).toISOString(),
        expires_at: new Date(Date.now() - 1 * 3600 * 1000).toISOString(),
        paid_at: new Date(Date.now() - 2 * 3600 * 1000).toISOString(),
        created_at: new Date(Date.now() - 2 * 3600 * 1000).toISOString(),
      },
    ],
    refunds: [],
    status_history: [
      {
        id: 'hist-01',
        order_id: 'ord-test-001',
        from_status: null,
        to_status: 'pending_payment',
        actor_type: 'customer',
        actor_id: 'cust-01',
        note: 'Sipariş oluşturuldu',
        created_at: new Date(Date.now() - 2 * 3600 * 1000).toISOString(),
      },
      {
        id: 'hist-02',
        order_id: 'ord-test-001',
        from_status: 'pending_payment',
        to_status: 'paid',
        actor_type: 'system',
        actor_id: null,
        note: 'PayTR ödeme onayı alındı',
        created_at: new Date(Date.now() - 2 * 3600 * 1000).toISOString(),
      },
    ],
    legal_acceptances: [
      {
        id: 'leg-01',
        order_id: 'ord-test-001',
        document_key: 'distance_sales_agreement',
        document_version: 'v1.0-2026-08',
        content_snapshot: {},
        accepted_at: new Date(Date.now() - 2 * 3600 * 1000).toISOString(),
      },
      {
        id: 'leg-02',
        order_id: 'ord-test-001',
        document_key: 'preliminary_information_form',
        document_version: 'v1.0-2026-08',
        content_snapshot: {},
        accepted_at: new Date(Date.now() - 2 * 3600 * 1000).toISOString(),
      },
    ],
  },
  {
    id: 'ord-test-002',
    order_number: 'VZ-20260829-002',
    customer_id: 'cust-02',
    customer_name: 'Mehmet Demir',
    customer_email: 'mehmet@example.com',
    customer_phone: '+90 532 987 6543',
    channel: 'retail',
    status: 'shipped',
    currency: 'TRY',
    tax_included: true,
    subtotal_minor: 850000,
    shipping_minor: 0,
    discount_minor: 0,
    tax_included_minor: 148750,
    total_minor: 850000,
    shipping_carrier: 'Yurtiçi Kargo',
    shipping_tracking_number: 'YK-987654321',
    shipping_tracking_url: 'https://yurticikargo.com/track/YK-987654321',
    cancellation_reason: null,
    admin_notes: null,
    created_at: new Date(Date.now() - 24 * 3600 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 12 * 3600 * 1000).toISOString(),
    paid_at: new Date(Date.now() - 24 * 3600 * 1000).toISOString(),
    cancelled_at: null,
    shipped_at: new Date(Date.now() - 12 * 3600 * 1000).toISOString(),
    delivered_at: null,
    shipping_address: {
      id: 'addr-02',
      user_id: 'cust-02',
      label: 'İş Adresi',
      recipient_name: 'Mehmet Demir',
      phone: '5329876543',
      address_line1: 'Maslak Plaza Kat: 12',
      address_line2: null,
      district: 'Sarıyer',
      city: 'İstanbul',
      state_province: null,
      postal_code: '34398',
      country_code: 'TR',
      country_name: 'Türkiye',
      is_default_shipping: true,
      is_default_billing: true,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    billing_address: {
      id: 'addr-02',
      user_id: 'cust-02',
      label: 'İş Adresi',
      recipient_name: 'Mehmet Demir',
      phone: '5329876543',
      address_line1: 'Maslak Plaza Kat: 12',
      address_line2: null,
      district: 'Sarıyer',
      city: 'İstanbul',
      state_province: null,
      postal_code: '34398',
      country_code: 'TR',
      country_name: 'Türkiye',
      is_default_shipping: true,
      is_default_billing: true,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    items: [
      {
        id: 'item-02',
        order_id: 'ord-test-002',
        product_id: 'prod-02',
        variant_id: 'var-02',
        sku_snapshot: 'VZ-LUNA-M',
        product_name_snapshot: 'Luna Heykelsi Vazo',
        variant_name_snapshot: 'Krem / Orta (28cm)',
        image_url_snapshot: 'https://images.unsplash.com/photo-1612196808214-b8e1d6145a8c?auto=format&fit=crop&q=80&w=800',
        unit_price_minor: 850000,
        quantity: 1,
        line_total_minor: 850000,
        currency: 'TRY',
        channel: 'retail',
        metadata_snapshot: {},
        created_at: new Date().toISOString(),
      },
    ],
    payments: [
      {
        id: 'pay-002',
        order_id: 'ord-test-002',
        order_number: 'VZ-20260829-002',
        customer_email: 'mehmet@example.com',
        provider: 'paytr',
        merchant_oid: 'VZ20260829002TX1',
        status: 'paid',
        expected_amount_minor: 850000,
        refunded_amount_minor: 0,
        currency: 'TRY',
        test_mode: true,
        failure_code: null,
        failure_message_safe: null,
        initiated_at: new Date(Date.now() - 24 * 3600 * 1000).toISOString(),
        expires_at: new Date(Date.now() - 23 * 3600 * 1000).toISOString(),
        paid_at: new Date(Date.now() - 24 * 3600 * 1000).toISOString(),
        created_at: new Date(Date.now() - 24 * 3600 * 1000).toISOString(),
      },
    ],
    refunds: [],
    status_history: [
      {
        id: 'hist-03',
        order_id: 'ord-test-002',
        from_status: 'paid',
        to_status: 'shipped',
        actor_type: 'admin',
        actor_id: 'admin-01',
        note: 'Kargoya verildi: Yurtiçi Kargo (YK-987654321)',
        created_at: new Date(Date.now() - 12 * 3600 * 1000).toISOString(),
      },
    ],
    legal_acceptances: [],
  },
];
