-- Migration: 20260910030000_enable_commerce_rls.sql
-- Description: Ensures Row Level Security (RLS) is strictly enabled on orders, order_items,
-- payments, payment_events, refunds, trade_applications, audit logs, and catalog tables.

ALTER TABLE IF EXISTS public.orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.order_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.payments ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.payment_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.refunds ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.trade_applications ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.admin_audit_logs ENABLE ROW LEVEL SECURITY;

ALTER TABLE IF EXISTS public.categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.collections ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.products ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.product_variants ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.product_media ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.product_categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.product_collections ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.wholesale_price_tiers ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.wholesale_benefits ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.announcement_bars ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.hero_slides ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.editorial_sections ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.menu_groups ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.menu_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.site_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.shipping_zones ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.shipping_rates ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.shipping_zone_countries ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.content_pages ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.content_sections ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.faq_groups ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.faq_items ENABLE ROW LEVEL SECURITY;
